name: 'Deploy /ipns/xkcd.hacdias.com'
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: output
          key: xkcd-clone-1.2.1
      - run: npx xkcd-clone -d output
      - run: npx ipfs-deploy output -C -O -u pinata -p ipfs-cluster -d cloudflare
        env:
          IPFS_DEPLOY_CLOUDFLARE__ZONE: hacdias.com
          IPFS_DEPLOY_CLOUDFLARE__RECORD: _dnslink.xkcd.hacdias.com
          IPFS_DEPLOY_CLOUDFLARE__API_TOKEN: ${{ secrets.IPFS_DEPLOY_CLOUDFLARE__API_TOKEN }}
          IPFS_DEPLOY_IPFS_CLUSTER__HOST: ${{ secrets.IPFS_DEPLOY_IPFS_CLUSTER__HOST }}
          IPFS_DEPLOY_IPFS_CLUSTER__PASSWORD: ${{ secrets.IPFS_DEPLOY_IPFS_CLUSTER__PASSWORD }}
          IPFS_DEPLOY_IPFS_CLUSTER__USERNAME: ${{ secrets.IPFS_DEPLOY_IPFS_CLUSTER__USERNAME }}
          IPFS_DEPLOY_PINATA__API_KEY: ${{ secrets.IPFS_DEPLOY_PINATA__API_KEY }}
          IPFS_DEPLOY_PINATA__SECRET_API_KEY: ${{ secrets.IPFS_DEPLOY_PINATA__SECRET_API_KEY }}
